### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by mdj2812** [Synodra/EasyPark#4]
# To do
- [x] Change node id to integers
- [x] Display the status of nodes in real temps on admin site
- [x] Make a system which will ensure the sensor working properly
- [x] Find a way to calibrate sensors
